### ISSUE TITLE
`pack.yaml` is missing

### ISSUE THREAD

**Issue by emedvedev** [aniruddhamonker/tshoot_brocadeVDX#1]
The `pack.yaml` file for the pack definition and metadata is missing, so it's not a real pack as such: I can't install it with `packs.install` in my st2 instance.

You can find examples of `pack.yaml` files either in [the docs](https://docs.stackstorm.com/reference/packs.html#my-first-pack) or [our contrib repo](https://github.com/stackstorm/st2contrib).

**Comment by aniruddhamonker** [comment]
created pack.yaml  with pack information and metadata

**Comment by emedvedev** [comment]
Perfect! Closing the issue. :)
