### ISSUE TITLE
Naming issues

### ISSUE THREAD

**Issue by emedvedev** [aniruddhamonker/tshoot_brocadeVDX#2]
There's a few different problems with the naming of actions/rules/sensors:
1. Normally, your repo would be named same as your pack. `ST2_projects` is a very generic name and doesn't reflect what the pack is for. If your pack is called `amonkervdx`, then the repo should be named that, too (or with a prefix to set it apart in the list: `stackstorm-amonkervdx`.
2. Try to follow conventions with your action/rule/sensor filenames, too: for example, the name of the file containing the action yaml/code should ideally be the same as the name of the action in the yaml (even if technically it will work without that requirement).
3. As far as the naming conventions go, we don't have anything strict, but it's usually a good idea to check packs in https://github.com/stackstorm/st2contrib before you name your actions/rules. Lowercase is a strong preference, underscores are preferred but not enforced. So `List_DiskConsuming_Files_VDX` would be `list_diskconsuming_files_vdx`. I know it's not ideal, but we try to maintain consistency where reasonable.
4. Make sure the `pack` parameter inside your rules corresponds to the actual pack name.

**Comment by aniruddhamonker** [comment]
Changed repo name to "tshoot_brocadeVDX" to reflect the pack name.

**Comment by aniruddhamonker** [comment]
corrected action and sensor names under metadata files to reflect the actual filenames.
changed trigger name to all lower case
